# Some examples of the need for functions with more than one input or output

```
using CalculusWithJulia
```

## Parameterized curves



## Functions of more than one variable

A familiar [childhood game](https://en.wikipedia.org/wiki/Huckle_buckle_beanstalk) involve one child seeking a hidden object while others call out "warmer" or "colder," as the seeker moves around. To model such a game mathematically, we would need to describe the direction of the  motion of the walker and then use this to determine if the motion takes the walker closer or farther from the hidden object.


A similar game -- likely never to catch on, but easier to describe mathematically, could have the kids speak out numbers between $0$ and $1$ with larger numbers meaning closer to the object. This games requires the seeker to identify that they are getting closer by keeping track of whether their values are increasing or decreasing. A simple algorithm would have the seeker always trying to increase their number until they have found the object.

Let's imagine a few scenarios. The person to find the object the quickest would try to move in such a way that the increase is maximal. In the simple game described, this would happen when the person is walking directly towards the object. Another child, trying to maximize their time in the spotlight might choose to make their quest a bit longer. If they didn't want to look silly by deliberately walking away from the object, they might try to keep their change on each step small but positive. It would be possible to always keep the change at $0$. A bit of thought would see that in this simple game this would be done by walking in a circle around the object.



In this game, there is a natural mapping between a position, $(x,y)$, and a value, say $z$. How would that be modeled? Well with a function of course. Such a function would take two values as inputs, an $x$ and a $y$ value, so might be written as:

$$~
z = f(x,y)
~$$

A model for this game might be `f(x,y) = max(0, 1 - (x^2 + y^2))` where the object is at the origin. We use `julia` notation, as we have already encountered the fact that functions in `julia` can naturally accept more than one variable.
For example the area of a rectangle as a function of width and height can be defined through: `area(w, h) = w * h`. 

These functions have as their input two variables and their output a single (scalar) value. Though slightly different from scalar-valued functions of a single variable, the idea still fits within the more general notion of a [function](http://tinyurl.com/c2rwqyb).


The children calling out the numbers may not be so mathematically inclined or they may be more inclined but a bit devious. They could come up with other functions that go to $1$ as the child gets closer, but not in such a symmetric way. For example: `f(x,y) = max(0, 1 - (2x^2 + y^2))`. The exact routes to the fastest solution or the route to stay exactly a fixed value away would change here. How? Well, these questions can be mathematically defined, bu tnot now.




There are many other examples where more complicated functions naturally arise. For example,consider a bird soaring through the sky. Birds may look for a boost upward from updrafts due to thermal differences, as this makes their flight easier. A model for such boosts, might assign a value (the size of the upward push, say) to each position in the space the bird might fly. In this case, the function might be $b = f(x,y,z)$, as there are three dimensions the bird can move in. Or if time is included, as would be natural, $b = f(x,y,z,t)$.

Again, this would still fit the general notion of a function.



> Scalar-valued functions (real-value function) of two or more real variables. A function $y = f(x_1, x_2, \dots, x_n)$ with $n$ real inputs and a single real-value for output is called a scalar-value function of two or more real variables.


Here are so more examples:

* a function which just adds values would be $f(x,y) = x + y$.

* a function which treats the values as a vector and returns the norm would be $f(x,y)  = \sqrt{x^2 + y^2}$. More generally, this could be $f(x_1, x_2, \dots, x_n) = \sqrt{x_1^2 + \cdots x_n^2}$.

* a hiker with a watch that returns the elevation traverses an area with height given by $a = h(x,y)$. For example, $h(x,y) = 500 - (x^2 + 2y^2)$.

* The force of gravity on planet due to the sun that is at a postition described by $x$, $y$, and $z$ would be modeled by

$$~
f(x,y,z) = G \frac{m_1 \cdot m_2}{x^2 + y^2 + z^2}.
~$$


XXX Natural questions: visualization, rates of change, volumes related to these functions


## Functions from $R^m$ to $R^n$
