# Scalar-valued function of two or more variables.

```
using CalculusWithJulia
```

##

A familiar [childhood game](https://en.wikipedia.org/wiki/Huckle_buckle_beanstalk) involve one child seeking a hidden object while others call out "warmer" or "colder," as the seeker moves around. A similar game -- likely never to catch on -- could have the kids speak out numbers between $0$ and $1$ with larger numbers meaning closer to the object. The clever child would then move to increase their number until they arrive at their spot.


In this game, there is a natural mapping between a position, $(x,y)$, and a value, say $z$. How would that be modeled? Well with a function of course. Such a function would take two values as inputs, an $x$ and a $y$ value, so might be written as:

$$~
z = f(x,y)
~$$

This function is a function of two variables which returns a single (scalar) value. Though slightly different from scalar-valued functions of a single variable, the idea still fits within the more general notion of a [function](http://tinyurl.com/c2rwqyb).


Another example, might have a bird soaring through the sky. Birds may look for a boost upward from updrafts due to thermal differences, as this makes their flight easier. A model for such boosts, might assign a value (the size of the upward push, say) to each position in the space the bird might fly. In this case, the function might be $b = f(x,y,z)$, as there are three dimensions the bird can move in. Or if time is included, as would be natural, $b = f(x,y,z,t)$.

Again, this would still fit the general notion of a function.



> Scalar-valued functions (real-value function) of two or more real variables. A function $y = f(x_1, x_2, \dots, x_n)$ with $n$ real inputs and a single real-value for output is called a scalar-value function of two or more real variables.


There are many possible examples:

* a function which just adds values would be $f(x,y) = x + y$.

* a function which treats the values as a vector and returns the norm would be $f(x,y)  = \sqrt{x^2 + y^2}$. More generally, this could be $f(x_1, x_2, \dots, x_n) = \sqrt{x_1^2 + \cdots x_n^2}$.

* a hiker with a watch that returns the elevation traverses an area with height given by $a = h(x,y)$. For example, $h(x,y) = 500 - (x^2 + 2y^2)$.

* The force of gravity on planet due to the sun that is at a postition described by $x$, $y$, and $z$ would be modeled by

$$~
f(x,y,z) = G \frac{m_1 \cdot m_2}{x^2 + y^2 + z^2}.
~$$




# visualization


surface plot

contour plot


