
# Continuity

The definition google finds for *continuous* is *forming an unbroken whole; without interruption*.

The concept in calculus, as transferred to functions, is similar. Roughly speaking, a continuous function is one whose graph could be drawn without having to lift the pencil drawing it.

Consider these two graphs:
<div id="6e80c123-d7ce-43c3-ba98-fa5486836d47" style="width:600px;height:400px;"></div>
<script>
PLOT = document.getElementById('6e80c123-d7ce-43c3-ba98-fa5486836d47');
Plotly.plot(PLOT, [{"yaxis":"y","y":[-1,-1],"showlegend":true,"name":"y1","type":"scatter","xaxis":"x","line":{"width":5,"dash":"solid","color":"rgba(0, 0, 0, 1.000)","shape":"linear"},"x":[-1,0],"mode":"lines"},{"yaxis":"y","y":[1,1],"showlegend":true,"name":"y2","type":"scatter","xaxis":"x","line":{"width":5,"dash":"solid","color":"rgba(0, 0, 0, 1.000)","shape":"linear"},"x":[0,1],"mode":"lines"}], {"yaxis":{"type":"-","titlefont":{"size":15,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"title":"","tickfont":{"size":11,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"ticks":"inside","tickmode":"array","showgrid":true,"tickvals":[-1.0,-0.5,0.0,0.5,1.0],"domain":[0.03762029746281716,0.9901574803149606],"ticktext":["-1.0","-0.5","0.0","0.5","1.0"],"tickangle":0,"zeroline":false,"linecolor":"rgba(0, 0, 0, 1.000)","tickcolor":"rgba(0, 0, 0, 1.000)","anchor":"x"},"annotations":[],"width":600,"plot_bgcolor":"rgba(255, 255, 255, 1.000)","showlegend":false,"xaxis":{"type":"-","titlefont":{"size":15,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"title":"","tickfont":{"size":11,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"ticks":"inside","tickmode":"array","showgrid":true,"tickvals":[-1.0,-0.5,0.0,0.5,1.0],"domain":[0.0658209390492855,0.9934383202099738],"ticktext":["-1.0","-0.5","0.0","0.5","1.0"],"tickangle":0,"zeroline":false,"linecolor":"rgba(0, 0, 0, 1.000)","tickcolor":"rgba(0, 0, 0, 1.000)","anchor":"y"},"paper_bgcolor":"rgba(255, 255, 255, 1.000)","height":400,"margin":{"r":0,"l":0,"b":0,"t":20}});
</script>

and
<div id="b201d1e1-8b5b-412d-b3b4-bbe1dd06d7ca" style="width:600px;height:400px;"></div>
<script>
PLOT = document.getElementById('b201d1e1-8b5b-412d-b3b4-bbe1dd06d7ca');
Plotly.plot(PLOT, [{"yaxis":"y","y":[-1,-1,1,1],"showlegend":true,"name":"y1","type":"scatter","xaxis":"x","line":{"width":5,"dash":"solid","color":"rgba(0, 0, 0, 1.000)","shape":"linear"},"x":[-1.0,-0.1,0.1,1.0],"mode":"lines"}], {"yaxis":{"type":"-","titlefont":{"size":15,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"title":"","tickfont":{"size":11,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"ticks":"inside","tickmode":"array","showgrid":true,"tickvals":[-1.0,-0.5,0.0,0.5,1.0],"domain":[0.03762029746281716,0.9901574803149606],"ticktext":["-1.0","-0.5","0.0","0.5","1.0"],"tickangle":0,"zeroline":false,"linecolor":"rgba(0, 0, 0, 1.000)","tickcolor":"rgba(0, 0, 0, 1.000)","anchor":"x"},"annotations":[],"width":600,"plot_bgcolor":"rgba(255, 255, 255, 1.000)","showlegend":false,"xaxis":{"type":"-","titlefont":{"size":15,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"title":"","tickfont":{"size":11,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"ticks":"inside","tickmode":"array","showgrid":true,"tickvals":[-1.0,-0.5,0.0,0.5,1.0],"domain":[0.0658209390492855,0.9934383202099738],"ticktext":["-1.0","-0.5","0.0","0.5","1.0"],"tickangle":0,"zeroline":false,"linecolor":"rgba(0, 0, 0, 1.000)","tickcolor":"rgba(0, 0, 0, 1.000)","anchor":"y"},"paper_bgcolor":"rgba(255, 255, 255, 1.000)","height":400,"margin":{"r":0,"l":0,"b":0,"t":20}});
</script>

Though similar at some level, the first has a "jump" from $-1$ to $1$ instead of the transition in the second one. The first is not continuous at $0$ – a break is needed to draw it – where as the second is continuous.

A formal definition was a bit harder to come to. At [first](http://en.wikipedia.org/wiki/Intermediate_value_theorem) the concept that for any $y$ between any two values in the range for $f(x)$, the function should take the value $y$ was included. [Cauchy](http://en.wikipedia.org/wiki/Cours_d%27Analyse) defined continuity by $f(x + \alpha) - f(x)$ being small whenever $\alpha$ was small. This basically rules out "jumps".

The [modern](http://en.wikipedia.org/wiki/Continuous_function#History) definition simply pushes the details to the definition of the limit:

> A function $f(x)$ is continuous at $x=c$ if $\lim_{x \rightarrow c}f(x) = f(c)$.


This says three things

  * The limit exists at $c$.
  * The function is defined at $c$ ($c$ is in the domain).
  * The value of the limit is the same as $f(c)$.

This speaks to continuity at a point, we can extend this to continuity over an interval $(a,b)$ by saying:

> A function $f(x)$ is continuous over $(a,b)$ if at each point $c$ with $a < c < b$, $f(x)$ is continuous at $c$.


Finally, as with limits, it can be convenient to speak of *right* continuity and *left* continuity at a point, where the limit in the defintion is replaced by a right or left limit, as appropriate.
<div class="alert alert-success" role="alert">
<div class="markdown"><p>The limit in the definition of continuity is the basic limit and not an extended sense where  infinities are accounted for. As with limits, such extensions are qualified in the language,  as in "<em>right</em> continous."</p>
</div> 
</div>

##### Examples of continuity

Most familiar functions are continuous everywhere.

  * For example, a monomial function $f(x) = ax^n$ for non-negative,

integer $n$ will be continuous. This is because the limit exists every where, the domain of $f$ is all $x$ and there are no jumps.

  * Similarly, the basic trigonometric functions $\sin(x)$, $\cos(x)$

are continuous everywhere.

  * So are the exponential functions $f(x) = a^x, a > 0$.
  * The hyperbolic sine ($(e^x - e^{-x})/2$) and cosine ($(e^x + e^{-x})/2$) are, as $e^x$ is.
  * The hyperbolic tangent is, as $\cosh(x) > 0$ for all $x$.

Some familiar functions are continuous but not everywhere.

  * For example, $f(x) = \sqrt{x}$ is continuous on $(0,\infty)$ and

right continuous at $0$. But it is not defined for negative $x$, so can't possibly be continuous there.

  * Similarly, $f(x) = \log(x)$ is continuous on $(0,\infty)$, but it is

not defined at $x=0$, so is not right continuous at $0$.

  * The tangent function $\tan(x) = \sin(x)/\cos(x)$ is continuous everywhere *except* the points $x$ with $\cos(x) = 0$ ($\pi/2 + k\pi, k$ an integer).
  * The hyperbolic co-tangent is not continuous at $x=0$ when $\sinh$ is $0$,
  * The semicircle $f(x) = \sqrt{1 - x^2}$ is *continous* on $(-1, 1)$. It is not continous at $-1$ and $1$, though it is right continuous at $-1$ and left continous at $1$.

##### Examples of discontinuity

There are various reasons why a function may not be continuous.

  * The function $f(x) = \sin(x)/x$ has a limit at $0$ but is not defined at $0$, so is not continuous at $0$. The function can be redefined to make it continuous.
  * The function $f(x) = 1/x$ is continuous everywhere *except* $x=0$.
  * A rational function $f(x) = p(x)/q(x)$ will be continuous everywhere except where $q(x)=0$.
  * The function
$$~
f(x) = \begin{cases}
         -1 & x < 0 \\
          0 & x = 0 \\
          1 & x > 0
\end{cases}
~$$

is implemented by `Julia`'s `sign` function. It has a value at $0$, but no limit at $0$, so is not continuous at $0$. Furthermore, the left and right limits exist at $0$ but are not equal to $f(0)$ so the function is not left or right continuous at $0$. It is continous everywhere except at $x=0$.

  * Similarly, the function defined by this graph
<div id="65e9de77-444d-4989-856c-aee6dfd09e6f" style="width:600px;height:400px;"></div>
<script>
PLOT = document.getElementById('65e9de77-444d-4989-856c-aee6dfd09e6f');
Plotly.plot(PLOT, [{"yaxis":"y","y":[-1.0,-0.01],"showlegend":true,"name":"y1","type":"scatter","xaxis":"x","line":{"width":1,"dash":"solid","color":"rgba(0, 0, 0, 1.000)","shape":"linear"},"x":[-1.0,-0.01],"mode":"lines"},{"yaxis":"y","y":[0.01,1.0],"showlegend":true,"name":"y2","type":"scatter","xaxis":"x","line":{"width":1,"dash":"solid","color":"rgba(0, 0, 0, 1.000)","shape":"linear"},"x":[0.01,1.0],"mode":"lines"},{"yaxis":"y","y":[0.5],"showlegend":true,"name":"y3","type":"scatter","xaxis":"x","x":[0],"mode":"markers","marker":{"symbol":"circle","line":{"width":1,"color":"rgba(0, 0, 0, 1.000)"},"size":10,"color":"rgba(62, 164, 78, 1.000)"}}], {"yaxis":{"type":"-","titlefont":{"size":15,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"title":"","tickfont":{"size":11,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"ticks":"inside","tickmode":"array","showgrid":true,"tickvals":[-1.0,0.0,1.0],"domain":[0.03762029746281716,0.9901574803149606],"ticktext":["-1","0","1"],"tickangle":0,"zeroline":false,"linecolor":"rgba(0, 0, 0, 1.000)","tickcolor":"rgba(0, 0, 0, 1.000)","anchor":"x"},"annotations":[],"width":600,"plot_bgcolor":"rgba(255, 255, 255, 1.000)","showlegend":false,"xaxis":{"type":"-","titlefont":{"size":15,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"title":"","tickfont":{"size":11,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"ticks":"inside","tickmode":"array","showgrid":true,"tickvals":[-1.0,0.0,1.0],"domain":[0.03619130941965587,0.9934383202099738],"ticktext":["-1","0","1"],"tickangle":0,"zeroline":false,"linecolor":"rgba(0, 0, 0, 1.000)","tickcolor":"rgba(0, 0, 0, 1.000)","anchor":"y"},"paper_bgcolor":"rgba(255, 255, 255, 1.000)","height":400,"margin":{"r":0,"l":0,"b":0,"t":20}});
</script>

is not continuous at $x=0$. It has a limit of $0$ at $0$, a function value $f(0) =1/2$, but the limit and the function value are not equal.

  * The `floor` function, which rounds down to the nearest integer, is

also not continuous at the integers, but is right continuous at the integers, as, for example, $\lim_{x \rightarrow 0+} f(x) = f(0)$. This graph emphasizes the right continuity by placing a point for the value of the function when there is a jump:
<div id="d1241314-2dfd-4c9b-b3dc-22de78875713" style="width:600px;height:400px;"></div>
<script>
PLOT = document.getElementById('d1241314-2dfd-4c9b-b3dc-22de78875713');
Plotly.plot(PLOT, [{"yaxis":"y","y":[-2,-2],"showlegend":true,"name":"y1","type":"scatter","xaxis":"x","line":{"width":1,"dash":"solid","color":"rgba(0, 0, 0, 1.000)","shape":"linear"},"x":[-2,-1],"mode":"lines"},{"yaxis":"y","y":[-1,-1],"showlegend":true,"name":"y2","type":"scatter","xaxis":"x","line":{"width":1,"dash":"solid","color":"rgba(0, 0, 0, 1.000)","shape":"linear"},"x":[-1,0],"mode":"lines"},{"yaxis":"y","y":[0,0],"showlegend":true,"name":"y3","type":"scatter","xaxis":"x","line":{"width":1,"dash":"solid","color":"rgba(0, 0, 0, 1.000)","shape":"linear"},"x":[0,1],"mode":"lines"},{"yaxis":"y","y":[1,1],"showlegend":true,"name":"y4","type":"scatter","xaxis":"x","line":{"width":1,"dash":"solid","color":"rgba(0, 0, 0, 1.000)","shape":"linear"},"x":[1,2],"mode":"lines"},{"yaxis":"y","y":[2,2],"showlegend":true,"name":"y5","type":"scatter","xaxis":"x","line":{"width":1,"dash":"solid","color":"rgba(0, 0, 0, 1.000)","shape":"linear"},"x":[2,3],"mode":"lines"},{"yaxis":"y","y":[-2,-1,0,1,2],"showlegend":true,"name":"y6","type":"scatter","xaxis":"x","x":[-2,-1,0,1,2],"mode":"markers","marker":{"symbol":"circle","line":{"width":1,"color":"rgba(0, 0, 0, 1.000)"},"size":10,"color":"rgba(0, 170, 174, 1.000)"}}], {"yaxis":{"type":"-","titlefont":{"size":15,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"title":"","tickfont":{"size":11,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"ticks":"inside","tickmode":"array","showgrid":true,"tickvals":[-2.0,-1.0,0.0,1.0,2.0],"domain":[0.03762029746281716,0.9901574803149606],"ticktext":["-2","-1","0","1","2"],"tickangle":0,"zeroline":false,"linecolor":"rgba(0, 0, 0, 1.000)","tickcolor":"rgba(0, 0, 0, 1.000)","anchor":"x"},"annotations":[],"width":600,"plot_bgcolor":"rgba(255, 255, 255, 1.000)","showlegend":false,"xaxis":{"type":"-","titlefont":{"size":15,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"title":"","tickfont":{"size":11,"color":"rgba(0, 0, 0, 1.000)","family":"Helvetica"},"ticks":"inside","tickmode":"array","showgrid":true,"tickvals":[-2.0,0.0,2.0],"domain":[0.03619130941965587,0.9934383202099738],"ticktext":["-2","0","2"],"tickangle":0,"zeroline":false,"linecolor":"rgba(0, 0, 0, 1.000)","tickcolor":"rgba(0, 0, 0, 1.000)","anchor":"y"},"paper_bgcolor":"rgba(255, 255, 255, 1.000)","height":400,"margin":{"r":0,"l":0,"b":0,"t":20}});
</script>

  * The function $f(x) = 1/x^2$ is not continuous at $x=0$: $f(x)$ is not

defined at $x=0$ and $f(x)$ has no limit at $x=0$ (in the usual sense).

  * On the Wikipedia page for [continuity](https://en.wikipedia.org/wiki/Continuous_function) the example of Dirichlet's function is given:
$$~
f(x) = \begin{cases}
0 & \text{if } x \text{ is irrational,}\\
1 & \text{if } x \textP is rational.}
~$$

The limit for any $c$ is discontinuous, as any interval about $c$ will contain *both* rational and irrational numbers so the function will not take values in a small neighborhood around any potential $L$.

## Rules for continuity

As we've seen, functions can be combined in several ways. How do these relate with continuity?

Suppose $f(x)$ and $g(x)$ are both continuous on $(a,b)$. Then

  * $$
    h(x) = \alpha f(x) + \beta g(x)
    $$

    is continuous on $(a,b)$ for any real numbers $\alpha$ and $\beta$;
  * $$
    h(x) = f(x) \cdot g(x)
    $$

    is continuous on $(a,b)$; and
  * $$
    h(x) = f(x) / g(x)
    $$

    is continuous at all points $c$ in $(a,b)$ where $g(c) \neq 0$.

Finally, if $g(x)$ is continuous at $c$ *and* $f(x)$ is continous at $g(c)$, then $f \circ g$ is continuous at $c$.

So, continuity is preserved for all of the basic operations except when dividing by $0$.

##### Examples

  * Since a monomial $f(x) = ax^n$ ($n$ a non-negative integer) is continuous, by the first rule, any polynomial will be continuous.
  * Since both $f(x) = e^x$ and $g(x)=\sin(x)$ are continuous everywhere, so will be $h(x) = e^x \cdot \sin(x)$.
  * Since $f(x) = e^x$ is continuous everywhere and $g(x) = -x$ is

continuous everywhere, the composition $h(x) = e^{-x}$ will be continuous everywhere.

  * Since $f(x) = x$ is continuous everywhere, the function $h(x) = 1/x$ –

a ratio of continuous functions – will be continuous everywhere *except* possibly at $x=0$ (where it is not continuous).

  * The function $h(x) = e^{x\log(x)}$ will be continuous on $(0,\infty)$,

the same domain that $g(x) = x\log(x)$ is continuous. This function (also written as $x^x$) has a right limit at $0$ (of $1$), but is not right continuous, as $h(0)$ is not defined.

## Questions

###### Question

Let $f(x) = \sin(x)$ and $g(x) = \cos(x)$. Which of these is not continuous everywhere?
$$~
f+g,~ f-g,~ f\cdot g,~ f\circ g,~ f/g
~$$

----

<form name="WeaveQuestion" data-id="rndsaEeY" data-controltype="radio">
<div class="form-group ">

<div  class="radio"> 
<label>
<input type="radio" name="radio_rndsaEeY" value="1"><div class="markdown">$f\cdot g$
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_rndsaEeY" value="2"><div class="markdown">$f-g$
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_rndsaEeY" value="3"><div class="markdown">$f+g$
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_rndsaEeY" value="4"><div class="markdown">$f/g$
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_rndsaEeY" value="5"><div class="markdown">$f\circ g$
</div>
</label>
</div>



<div id="rndsaEeY_message"></div>
</div>
</form>
<script text="text/javascript">
$("input:radio[name='radio_rndsaEeY']").on("change", function() {
correct = this.value == 4;

if(correct) {
$("#rndsaEeY_message").html("<div class='alert alert-success'><span class='glyphicon glyphicon-thumbs-up'>&nbsp;Correct</span></div>");
} else {
$("#rndsaEeY_message").html("<div class='alert alert-warning'><span class='glyphicon glyphicon-thumbs-down'>&nbsp;Incorrect</span></div>");
}
});

</script>

----



###### Question

Let $f(x) = \sin(x)$, $g(x) = \sqrt{x}$.

When will $f\circ g$ be continuous?

----

<form name="WeaveQuestion" data-id="xREuPk7o" data-controltype="radio">
<div class="form-group ">

<div  class="radio"> 
<label>
<input type="radio" name="radio_xREuPk7o" value="1"><div class="markdown"><p>For all $x$</p>
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_xREuPk7o" value="2"><div class="markdown"><p>For all $x > 0$</p>
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_xREuPk7o" value="3"><div class="markdown"><p>For all $x$ where $\sin(x) > 0$</p>
</div>
</label>
</div>



<div id="xREuPk7o_message"></div>
</div>
</form>
<script text="text/javascript">
$("input:radio[name='radio_xREuPk7o']").on("change", function() {
correct = this.value == 2;

if(correct) {
$("#xREuPk7o_message").html("<div class='alert alert-success'><span class='glyphicon glyphicon-thumbs-up'>&nbsp;Correct</span></div>");
} else {
$("#xREuPk7o_message").html("<div class='alert alert-warning'><span class='glyphicon glyphicon-thumbs-down'>&nbsp;Incorrect</span></div>");
}
});

</script>

----



When will $g \circ f$ be continuous?

----

<form name="WeaveQuestion" data-id="K5qwVRAL" data-controltype="radio">
<div class="form-group ">

<div  class="radio"> 
<label>
<input type="radio" name="radio_K5qwVRAL" value="1"><div class="markdown"><p>For all $x$</p>
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_K5qwVRAL" value="2"><div class="markdown"><p>For all $x > 0$</p>
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_K5qwVRAL" value="3"><div class="markdown"><p>For all $x$ where $\sin(x) > 0$</p>
</div>
</label>
</div>



<div id="K5qwVRAL_message"></div>
</div>
</form>
<script text="text/javascript">
$("input:radio[name='radio_K5qwVRAL']").on("change", function() {
correct = this.value == 3;

if(correct) {
$("#K5qwVRAL_message").html("<div class='alert alert-success'><span class='glyphicon glyphicon-thumbs-up'>&nbsp;Correct</span></div>");
} else {
$("#K5qwVRAL_message").html("<div class='alert alert-warning'><span class='glyphicon glyphicon-thumbs-down'>&nbsp;Incorrect</span></div>");
}
});

</script>

----



###### Question

The composition $f\circ g$ will be continuous everywhere provided:

----

<form name="WeaveQuestion" data-id="1I2vekTm" data-controltype="radio">
<div class="form-group ">

<div  class="radio"> 
<label>
<input type="radio" name="radio_1I2vekTm" value="1"><div class="markdown"><p>The function $g$ is continuous everywhere</p>
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_1I2vekTm" value="2"><div class="markdown"><p>The function $f$ is continuous everywhere</p>
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_1I2vekTm" value="3"><div class="markdown"><p>The function $g$ is continuous everywhere and $f$ is continuous on the range of $g$</p>
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_1I2vekTm" value="4"><div class="markdown"><p>The function $f$ is continuous everywhere and $g$ is continuous on the range of $f$</p>
</div>
</label>
</div>



<div id="1I2vekTm_message"></div>
</div>
</form>
<script text="text/javascript">
$("input:radio[name='radio_1I2vekTm']").on("change", function() {
correct = this.value == 3;

if(correct) {
$("#1I2vekTm_message").html("<div class='alert alert-success'><span class='glyphicon glyphicon-thumbs-up'>&nbsp;Correct</span></div>");
} else {
$("#1I2vekTm_message").html("<div class='alert alert-warning'><span class='glyphicon glyphicon-thumbs-down'>&nbsp;Incorrect</span></div>");
}
});

</script>

----



###### Question

At which values is $f(x) = 1/\sqrt{x-2}$ not continuous?

----

<form name="WeaveQuestion" data-id="n1JkMWx4" data-controltype="radio">
<div class="form-group ">

<div  class="radio"> 
<label>
<input type="radio" name="radio_n1JkMWx4" value="1"><div class="markdown"><p>When $x \geq 2$</p>
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_n1JkMWx4" value="2"><div class="markdown"><p>When $x \leq 2$</p>
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_n1JkMWx4" value="3"><div class="markdown"><p>For $x \geq 0$</p>
</div>
</label>
</div>

<div  class="radio"> 
<label>
<input type="radio" name="radio_n1JkMWx4" value="4"><div class="markdown"><p>When $x > 2$</p>
</div>
</label>
</div>



<div id="n1JkMWx4_message"></div>
</div>
</form>
<script text="text/javascript">
$("input:radio[name='radio_n1JkMWx4']").on("change", function() {
correct = this.value == 2;

if(correct) {
$("#n1JkMWx4_message").html("<div class='alert alert-success'><span class='glyphicon glyphicon-thumbs-up'>&nbsp;Correct</span></div>");
} else {
$("#n1JkMWx4_message").html("<div class='alert alert-warning'><span class='glyphicon glyphicon-thumbs-down'>&nbsp;Incorrect</span></div>");
}
});

</script>

----



###### Question

A value $x=c$ is a *removable singularity* for $f(x)$ if $f(x)$ is not continuous at $c$ but will be if $f(c)$ is redefined to be $\lim_{x \rightarrow c} f(x)$.

The function $f(x) = (x^2 - 4)/(x-2)$ has a removable singularity at $x=2$. What value would we redefine $f(2)$ to be, to make $f$ a continuous function?

----

<form name='WeaveQuestion' data-id='9VE6c2Bv' data-controltype='numeric'>
<div class='form-group '>
<div class='controls'>



<div class="input-group">
<input id="9VE6c2Bv" type="number" class="form-control">

</div>

<div id='9VE6c2Bv_message'></div>
</div>
</div>
</form>
<script text='text/javascript'>
$('#9VE6c2Bv').on('change', function() {
correct = Math.abs(this.value - 4.000010000000827) <= 0.001;

if(correct) {
$('#9VE6c2Bv_message').html('<div class="alert alert-success"><span class="glyphicon glyphicon-thumbs-up">&nbsp;Correct</span></div>');
} else {
$('#9VE6c2Bv_message').html('<div class="alert alert-danger"><span class="glyphicon glyphicon-thumbs-down">&nbsp;Incorrect</span></div>');
}
});
</script>

----



###### Question

The highly oscillatory function 
$$~
f(x) = x^2 (\cos(1/x) - 1)
~$$

has a removable singularity at $x=0$. What value would we redefine $f(0)$ to be, to make $f$ a continuous function?

----

<form name='WeaveQuestion' data-id='3BIp5qAo' data-controltype='numeric'>
<div class='form-group '>
<div class='controls'>



<div class="input-group">
<input id="3BIp5qAo" type="number" class="form-control">

</div>

<div id='3BIp5qAo_message'></div>
</div>
</div>
</form>
<script text='text/javascript'>
$('#3BIp5qAo').on('change', function() {
correct = Math.abs(this.value - 0) <= 0.001;

if(correct) {
$('#3BIp5qAo_message').html('<div class="alert alert-success"><span class="glyphicon glyphicon-thumbs-up">&nbsp;Correct</span></div>');
} else {
$('#3BIp5qAo_message').html('<div class="alert alert-danger"><span class="glyphicon glyphicon-thumbs-down">&nbsp;Incorrect</span></div>');
}
});
</script>

----



